#!/usr/bin/env python
# -*- encoding: utf-8 -*-
# Created on 2018-08-23 08:49:39
# Project: pyspiderlianxi

from pyspider.libs.base_handler import *
import pymongo


class Handler(BaseHandler):
    crawl_config = {
    }

    client = pymongo.MongoClient(host='localhost', port=27017)
    db = client['trip']

    @every(minutes=24 * 60)
    def on_start(self):
        self.crawl('https://www.tripadvisor.cn/Attractions-g294211-Activities-c47-China.html', callback=self.index_page,
                   validate_cert=False)

    @config(age=10 * 24 * 60 * 60)
    def index_page(self, response):
        for each in response.doc('div.listing_info > div.listing_title > a').items():
            self.crawl(each.attr.href, callback=self.detail_page, validate_cert=False)

    @config(priority=2)
    def detail_page(self, response):
        url = response.url,
        title = response.doc('title').text(),
        name = response.doc('#HEADING').text(),
        paiming = response.doc('span.header_rating > div > a > span').text(),
        phonenum = response.doc('div.blEntry.phone > span:nth-child(2)').text(),
        dizhi = response.doc('div.detail_section.address.xh-highlight').text(),
        youwanshijian = response.doc('#taplc_attraction_detail_listing_0 > div.section.hours > div').text()

        return {
            "url": url,
            "title": title,
            "name": name,
            "paiming": paiming,
            "phonenum": phonenum,
            "dizhi": dizhi,
            "youwanshijian": youwanshijian

        }

    def on_result(self, result):
        if result:
            self.save_to_mongo(result)

    def save_to_mongo(self, result):
        if self.db['chinastrip'].insert(result):
            print('save to mongo', result)
